" Cano's Vim Config Author: Cano
" Email: gcanoxl@gmail.com
"
" This config is lightweight, but smart development environment
" for Web front-end(HTML, CSS, JavaScript), python languages.
"
" You should install all tools of the list before use this config.
" List: git, curl, ctags, jedi, ipykernel, jupyter_client

" Enviroment initialization (compatible with neovim)
let g:VIM_HOME = expand('~/.vim')


if has('nvim')
    let g:VIM_HOME = expand('~/.config/nvim')
endif

" Vim-plug installation
" if vim-plug file (by default, it's VIM_HOME/autoload/plug.vim) is
" not exist, then download and install it from github.
let s:vim_plug_path = g:VIM_HOME.'/autoload/plug.vim'
if !filereadable(s:vim_plug_path)
    echo "Installing Vim-plug ..."
    echo ""
    let s:vim_plug_git = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    execute "!curl -fLo ".s:vim_plug_path." --create-dirs ".s:vim_plug_git
endif
let s:vim_plugged_path = g:VIM_HOME.'/plugged'

" Plugins Table
call plug#begin(s:vim_plugged_path)

" code browser
Plug 'majutsushi/tagbar'
Plug 'mattn/emmet-vim'

" file tree browser
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'

" python code completion
Plug 'davidhalter/jedi-vim', {'for': 'python'}
Plug 'Valloric/YouCompleteMe'
" ipython for nvim
Plug 'bfredl/nvim-ipy', {'for': 'python'}

" Syntax Checker
Plug 'neomake/neomake'
" vim-go
Plug 'fatih/vim-go'
Plug 'nsf/gocode', { 'rtp': 'vim', 'do': '~/.vim/plugged/gocode/vim/symlink.sh' }

" gist-vim
Plug 'lambdalisue/vim-gista'

" command fuzzy finder
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
" colorscheme
Plug 'nightsense/office'
Plug 'ayu-theme/ayu-vim' " or other package manager
Plug 'hzchirs/vim-material'
Plug 'nightsense/nemo'
Plug 'vim-airline/vim-airline'
Plug 'nightsense/forgotten'
Plug 'ajmwagar/vim-deus'
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'vim-airline/vim-airline-themes'
Plug 'altercation/vim-colors-solarized'
Plug 'morhetz/gruvbox'

" java
Plug 'artur-shaik/vim-javacomplete2'

" other
Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }
Plug 'davidoc/taskpaper.vim'
Plug 'vim-scripts/todo-vim'
Plug 'godlygeek/tabular'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-git'
Plug 'tpope/vim-surround'
Plug 'gregsexton/gitv', {'on': ['Gitv']}
Plug 'mhinz/vim-startify'
Plug 'scrooloose/nerdcommenter'
Plug 'Yggdroot/indentLine'
call plug#end()

" Automatic installation.
function! s:is_need_install()
    for l:plug_name in g:plugs_order
        let l:plug_path = s:vim_plugged_path.'/'.l:plug_name
        if !isdirectory(l:plug_path)
            return 1
        endif
    endfor
endfunction

if s:is_need_install()
    echom "Found new plugin(s) need to install."
    :PlugInstall
endif

" No vi-compatible
set nocompatible

" Allow plugins by file type
filetype plugin on
filetype indent on

" Use fisa colorscheme
set t_Co=256
syntax enable
"set background=dark
set background=dark
"colorscheme vim-material
hi Comment cterm=italic

" Ayu
set termguicolors     " enable true colors support
let ayucolor="light"  " for light version of theme
let ayucolor="mirage" " for mirage version of theme
let ayucolor="dark"   " for dark version of theme
colorscheme ayu

"" gui transparent
if has("gui_running")
    set shellcmdflag=-ic
    set transparency=10
endif

" airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='material'

" Show line numbers
let g:neomake_python_enabled_makers = ['python', 'flake8'] 
" Keep 3 lines when scrolling
set scrolloff=8

" Syntax highlight on
syntax on

" Always show status bar
set ls=2

" Incremental search
set incsearch
set hlsearch

" Tabs and spaces handling
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Tab length for different file type.
autocmd FileType html setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType css setlocal shiftwidth=4 tabstop=4 softtabstop=4
autocmd FileType javascript setlocal shiftwidth=4 tabstop=4 softtabstop=4

" Key Mappings {
let mapleader=' '

" mouse
set mouse=a
let mouseFlag =1
function! SetMouse()
    if g:mouseFlag == 1
        let g:mouseFlag=0
        set mouse=
        echo "mouse off"
    else
        let g:mouseFlag =1
        set mouse=a
        echo "mouse on"
    endif
endfunction

" set escape to jk
inoremap jk <ESC>
nmap <C-]> :TODOToggle<CR>
nmap <C-r> :!python3 %<CR>
" better command
nnoremap <silent> <leader>vs :vs<CR>

" general
nnoremap <silent> <leader>gq :xa<CR>
nnoremap <silent> <leader>ge :edit $MYVIMRC<CR>
nnoremap <silent> <leader>gr :source $MYVIMRC<CR>
nnoremap <silent> <leader>q :q! <CR>

" file
nnoremap <silent> <leader>fs :w<CR>
nnoremap <silent> <leader>fb :NERDTreeToggle<CR>

" buffer
nnoremap <silent> <leader>jf :%!python3 -m json.tool<CR>
nnoremap <silent> <leader>pdb :!python3 -m pdb %
nnoremap <silent> <leader>tg :TagbarToggle<CR>

" window
nnoremap <C-h> <C-w><C-h>
nnoremap <C-j> <C-w><C-j>
nnoremap <C-k> <C-w><C-k>
nnoremap <C-l> <C-w><C-l>
nnoremap <C-c> <C-w><C-c>
" nnoremap <C-o> <C-w><C-o>

if has("gui_running")
    set transparency=10
endif

" code
nnoremap <silent> <leader>sc :LeaderfBufTagAll<CR>
nnoremap <silent> <leader>sf :LeaderfFunction<CR>
nnoremap <silent> <leader>cb :TagbarToggle<CR>
nnoremap <silent> <leader>jts :JavaComplete-Generate-ToString<CR>
nnoremap <silent> <leader>gas :JCgenerateAccessorSetter<CR>
nnoremap <silent> <leader>gam :JCgenerateAbtractMethods <CR>

" NERDTree

" automatic open nerdtree when start up vim with a directory.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif

" automatic close nerdtree when only nerdtree window.
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Jedi

nmap <C-t> :call jedi#goto()<CR>
nmap <C-e> :call jedi#show_documentation() <CR>
nmap <C-n> :call jedi#usages()<CR>

map <C-x> :call SetMouse() <CR>
nmap <C-g> :Gitv <CR>

" PEP8

set tabstop=4
set softtabstop=4
set shiftwidth=4
set textwidth=99
set expandtab
set autoindent
" set fileformat=unix
" When writing a buffer.
call neomake#configure#automake('w')
" When writing a buffer, and on normal mode changes (after 750ms).
call neomake#configure#automake('nw', 750)
" When reading a buffer (after 1s), and when writing.
call neomake#configure#automake('rw', 1000)
set guioptions-=r " 隐藏右侧滚动条
set guioptions-=b " 隐藏底部滚动条
set guioptions-=L " 隐藏左侧滚动条
set guifont=SF\ MONO:h13
set clipboard=unnamed
set nohlsearch
set backspace=indent,eol,start
set nowrap
hi pythonSelf ctermfg=174 guifg=#6094DB cterm=bold gui=bold
set nu
set encoding=utf-8
set langmenu=zh_CN.UTF-8
"let g:indentLine_setColors = 0
language message zh_CN.UTF-8
let g:indentLine_color_term = 239
set noeb
"hi Normal     ctermbg=NONE guibg=NONE
"hi LineNr     ctermbg=NONE guibg=NONE
"hi SignColumn ctermbg=NONE guibg=NONE
let g:go_version_warning = 0
let g:SuperTabDefaultCompletionType = "<c-n>"
autocmd FileType java setlocal omnifunc=javacomplete#Complete

" java complete2 default map
nmap <leader>jI <Plug>(JavaComplete-Imports-AddMissing)
nmap <leader>jR <Plug>(JavaComplete-Imports-RemoveUnused)
nmap <leader>ji <Plug>(JavaComplete-Imports-AddSmart)
nmap <leader>jii <Plug>(JavaComplete-Imports-Add)

imap <C-j>I <Plug>(JavaComplete-Imports-AddMissing)
imap <C-j>R <Plug>(JavaComplete-Imports-RemoveUnused)
imap <C-j>i <Plug>(JavaComplete-Imports-AddSmart)
imap <C-j>ii <Plug>(JavaComplete-Imports-Add)

nmap <leader>jM <Plug>(JavaComplete-Generate-AbstractMethods)

imap <C-j>jM <Plug>(JavaComplete-Generate-AbstractMethods)

nmap <leader>jA <Plug>(JavaComplete-Generate-Accessors)
nmap <leader>js <Plug>(JavaComplete-Generate-AccessorSetter)
nmap <leader>jg <Plug>(JavaComplete-Generate-AccessorGetter)
nmap <leader>ja <Plug>(JavaComplete-Generate-AccessorSetterGetter)
nmap <leader>jts <Plug>(JavaComplete-Generate-ToString)
nmap <leader>jeq <Plug>(JavaComplete-Generate-EqualsAndHashCode)
nmap <leader>jc <Plug>(JavaComplete-Generate-Constructor)
nmap <leader>jcc <Plug>(JavaComplete-Generate-DefaultConstructor)

imap <C-j>s <Plug>(JavaComplete-Generate-AccessorSetter)
imap <C-j>g <Plug>(JavaComplete-Generate-AccessorGetter)
imap <C-j>a <Plug>(JavaComplete-Generate-AccessorSetterGetter)

vmap <leader>js <Plug>(JavaComplete-Generate-AccessorSetter)
vmap <leader>jg <Plug>(JavaComplete-Generate-AccessorGetter)
vmap <leader>ja <Plug>(JavaComplete-Generate-AccessorSetterGetter)

nmap <silent> <buffer> <leader>jn <Plug>(JavaComplete-Generate-NewClass)
nmap <silent> <buffer> <leader>jN <Plug>(JavaComplete-Generate-ClassInFile)
let g:SuperTabDefaultCompletionType = "<c-n>"

