# Oh-My-Zsh
export ZSH=$HOME/.dotfiles/oh-my-zsh

ZSH_THEME="cloud"

plugins=(git vi-mode)

source $ZSH/oh-my-zsh.sh

# set escape key to jk
bindkey -M viins 'jk' vi-cmd-mode

# ======================== ALIAS ========================
alias reload="source $HOME/.zshrc"

# git
alias gs="git status"
alias ga="git add"
alias gm="git commit -m"
