# Oh-My-Zsh
export ZSH=$HOME/.dotfiles/oh-my-zsh

ZSH_THEME="cloud"

plugins=(git archlinux)

source $ZSH/oh-my-zsh.sh

# set escape key to jk
# bindkey -M viins 'jk' vi-cmd-mode

# ======================== ALIAS ========================
alias reload="source $HOME/.zshrc"

# git
alias gs="git status"
alias ga="git add"
alias gm="git commit -m"

# tmux
alias tns="tmux new -s"
alias tls="tmux ls"
alias ta="tmux attach"
alias tt="tmux attach -t"
alias tks="tmux kill-sesion -t"
